<?php

declare(strict_types=1);

namespace Drupal\beta_onboarding\Form;

use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
final class BetaOnboardingAdminForm extends ConfigFormBase {

  protected function getEditableConfigNames()
  {
    return ["beta_onboarding.settings"];
  }

  public function getFormId()
  {
    return "beta_onboarding_admin_configuration_form";
  }

  public function buildForm(array $form, FormStateInterface $form_state)
  {
    $form["welcome_message"] = [
      '#type' => 'textfield',
      '#title' => $this->t("Some Welcome Message Goes Here"),
      '#default_value' => $this->config("beta_onboarding.settings")->get("welcome_message")
    ];
    return parent::buildForm($form, $form_state);
  }

  public function submitForm(array &$form, FormStateInterface $form_state)
  {
    $this->config("beta_onboarding.settings")
      ->set("welcome_message",$form_state->getValue("welcome_message"))
      ->save();
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
